name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: '^6.10.0'
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      # Install and build projects
      - run: pnpm install --frozen-lockfile
      # Run tests for all projects
      - run: pnpm test
      # Check code formatting
      - run: pnpx prettier --check .
