name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm i -g pnpm@6
      - uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      # Install and build projects
      - run: pnpm install
      # Run tests for all projects
      - run: pnpm test
      # Check code formatting
      - run: pnpx prettier --check .
      # Remove unreferenced packages from the store before caching to prevent the cache from growing.
      - run: pnpm store prune
